# Generated by Django 3.2.10 on 2022-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
